### ISSUE TITLE
german translation

### ISSUE THREAD

**Issue by zossebart** [Teester/Whats-Nearby#9]
As a native speaker of the german language, I find some of the german translations not quite ideal (especially the strings for "men", "women" and "cheques", but others could be improved too). I would like to improve them.
Where does the translation originate from? Did you use an external translation service or may I simply file a pull request?

**Comment by Teester** [comment]
The translations were done through Google Translate, so I'm not surprised that they could be improved.  I am not using a translation service (for now), so, by all means, submit a pull request.  Please submit against the <code>translations</code> branch.

**Comment by Teester** [comment]
Resolved by merge of #11
